import { Instagram, Play } from "lucide-react";
import Image from "next/image";
import { INSTAGRAM_URL } from "@/lib/constants";
import MotionReveal from "./MotionReveal";

export default function InstagramFeed(){
  // Replace placeholders with official BLU Marrakech reels or Instagram Graph API.
  const reels=["/images/card-live-singer.png","/images/card-cabaret.png","/images/card-dj.png","/images/card-vip.png","/images/blu-hero-cinematic.png","/images/card-cabaret.png"];
  return <section className="border-y border-white/5 bg-ink py-20 sm:py-24"><div className="site-container"><MotionReveal className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">@blu.marrakech_</p><h2 className="font-display text-4xl sm:text-6xl">Latest from Instagram</h2></div><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="btn-secondary self-start"><Instagram size={15}/> Suivre BLU</a></MotionReveal><div className="mt-10 grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-6">{reels.map((src,i)=><MotionReveal key={`${src}-${i}`} delay={i*.04}><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" aria-label={`Voir le reel BLU ${i+1}`} className="card-shine group relative block aspect-[9/14] overflow-hidden border border-white/10 bg-[#071126]"><Image src={src} alt={`Reel BLU Marrakech ${i+1}`} fill className="object-cover transition duration-700 group-hover:scale-110" sizes="(max-width:768px) 50vw, 17vw"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent to-ink/40"/><div className="absolute left-3 top-3 grid h-8 w-8 place-items-center rounded-full border border-white/20 bg-black/30 backdrop-blur transition group-hover:scale-110 group-hover:border-gold"><Play size={12} fill="currentColor"/></div><div className="absolute inset-x-0 bottom-0 p-3"><p className="text-[7px] uppercase tracking-[.2em] text-gold">Reel 0{i+1}</p><p className="mt-1 text-[9px] text-white/60">Live from the BLU</p></div></a></MotionReveal>)}</div></div></section>}
